[package]
name = "starklane"
version = "1.0.0"

[cairo]
sierra-replace-ids = true

[dependencies]
starknet = ">=1.0.0"

[[target.starknet-contract]]
sierra = true

[scripts]
test-caironet = "sudo docker run --rm -v $(pwd):/work -t --entrypoint cairo-test glihm/caironet:1.1.0-d --starknet /work/"

[lib]
