name: Contracts

on:
  push:
    branches: [main, dev]
    paths:
      - "apps/blockchain/**"
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

env:
  SCARB_VERSION: v0.6.0

jobs:
  build-starknet-contracts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Scarb
        run: |
          wget https://github.com/software-mansion/scarb/releases/download/${{ env.SCARB_VERSION }}/scarb-${{ env.SCARB_VERSION }}-x86_64-unknown-linux-gnu.tar.gz
          tar -xvzf scarb-${{ env.SCARB_VERSION }}-x86_64-unknown-linux-gnu.tar.gz
          echo "$GITHUB_WORKSPACE/scarb-${{ env.SCARB_VERSION }}-x86_64-unknown-linux-gnu/bin" >> $GITHUB_PATH

      - run: scarb build
        working-directory: apps/blockchain/contracts/starknet

  test-ethereum-contracts:
    strategy:
      fail-fast: true

    name: Foundry testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes --root apps/blockchain/contracts/ethereum/
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv --root apps/blockchain/contracts/ethereum/
        id: test

